'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={token:sessionStorage.getItem('restaurant-token'),user:null,dishes:[],cart:[],category:'Все',view:'menu',register:false};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:2}).format(n/100);
const statuses={new:'Новый',cooking:'Готовится',ready:'Готов к выдаче',completed:'Выдан',cancelled:'Отменён'};
let noticeTimer;
function notice(s){$('#notice').textContent=s;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('#notice').textContent='',6000)}
async function api(path,method='GET',body){let r;try{r=await fetch(window.API_BASE+path,{method,headers:{...(state.token?{Authorization:'Bearer '+state.token}:{}),...(body!==undefined?{'Content-Type':'application/json'}:{})},body:body===undefined?undefined:JSON.stringify(body)});}catch{throw Error('Сервер недоступен. Проверьте, запущен ли бэкенд.')}if(r.status===204)return null;const x=await r.json();if(!r.ok){if(r.status===401&&state.user){state.user=null;state.token=null;sessionStorage.removeItem('restaurant-token');state.cart=[];updateNav();if(state.view!=='menu')await show('menu')}throw Error(x.error||'Не удалось выполнить запрос')}return x}
async function action(fn){try{await fn()}catch(e){notice(e.message)}}
function updateNav(){$$('.private').forEach(n=>n.hidden=!state.user);$$('.admin-only').forEach(n=>n.hidden=state.user?.role!=='admin');$('#account').textContent=state.user?'Выйти':'Войти';$('#count').textContent=state.cart.reduce((s,i)=>s+i.quantity,0)}
function renderMenu(){const cats=['Все',...new Set(state.dishes.map(d=>d.category))];$('#categories').innerHTML=cats.map(c=>`<button class="chip ${state.category===c?'active':''}" data-cat="${esc(c)}" aria-pressed="${state.category===c}">${esc(c)}</button>`).join('');const query=$('#search').value.trim().toLowerCase();const ds=state.dishes.filter(d=>(state.category==='Все'||d.category===state.category)&&d.name.toLowerCase().includes(query));$('#dish-grid').innerHTML=ds.length?ds.map(d=>`<article class="card"><div class="card-art ${{'Супы':'soup','Горячее':'hot','Десерты':'sweet','Напитки':'drink'}[d.category]||''}" aria-hidden="true">${esc(d.category)}</div><div class="card-body"><h3>${esc(d.name)}</h3><p>${esc(d.description)}</p><p class="stock">${d.stock?'Доступно порций: '+d.stock:'Сегодня закончилось'}</p><div class="card-bottom"><span class="price">${money(d.price)}</span><button class="primary" data-add="${d.id}" ${!d.stock?'disabled':''}>${state.user?'В корзину':'Войти и заказать'}</button></div></div></article>`).join(''):'<p class="empty">По вашему запросу ничего не найдено.</p>'}
async function refresh(){state.dishes=await api('/dishes');if(state.user)state.cart=(await api('/cart')).items;else state.cart=[];updateNav();renderMenu()}
async function show(view){if(view!=='menu'&&!state.user){$('#auth-dialog').showModal();return}if(view==='admin'&&state.user.role!=='admin')return;state.view=view;$$('.view').forEach(s=>s.hidden=s.id!==view);$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='cart')await renderCart();if(view==='orders')await renderOrders();if(view==='admin')await renderAdmin();}
async function renderCart(){const c=await api('/cart');state.cart=c.items;updateNav();$('#cart-content').innerHTML=c.items.length?`<div class="panel">${c.items.map(i=>`<div class="row"><div><strong>${esc(i.name)}</strong><div class="muted">${money(i.price)} за порцию</div></div><div class="qty"><button data-qty="${i.id}" data-value="${i.quantity-1}" aria-label="Уменьшить ${esc(i.name)}">−</button><span>${i.quantity}</span><button data-qty="${i.id}" data-value="${i.quantity+1}" ${i.quantity>=i.stock||i.quantity>=99?'disabled':''} aria-label="Увеличить ${esc(i.name)}">+</button></div><strong>${money(i.price*i.quantity)}</strong><button class="text-btn" data-remove="${i.id}">Удалить</button></div>`).join('')}<div class="total"><strong>Итого</strong><strong>${money(c.total)}</strong></div><form id="checkout-form"><label for="comment">Комментарий к заказу</label><textarea id="comment" maxlength="300" placeholder="Например, положите приборы"></textarea><p class="muted">Самовывоз из ресторана. Оплата при получении. При оформлении цена и наличие повторно проверяются сервером.</p><button class="primary" type="submit">Оформить заказ</button></form></div>`:'<div class="empty"><h2>Ваша корзина пока пуста</h2><p>Выберите что-нибудь вкусное в меню.</p><button class="primary" data-view="menu">Перейти в меню</button></div>'}
function orderHTML(o,admin){let buttons='';if(admin){const next={new:['cooking','cancelled'],cooking:['ready'],ready:['completed']}[o.status]||[];buttons=next.map(s=>`<button class="secondary" data-status="${s}" data-order="${o.id}">${{cooking:'Начать готовить',ready:'Готов к выдаче',completed:'Выдать',cancelled:'Отменить'}[s]}</button>`).join('');if(o.status==='new')buttons+=`<button class="secondary" data-edit-items="${o.id}">Изменить состав</button>`}else if(o.status==='new')buttons=`<button class="secondary" data-cancel="${o.id}">Отменить заказ</button>`;return `<article class="order"><div class="order-top"><h3>Заказ № ${o.id}</h3><span class="badge">${statuses[o.status]}</span></div><p class="muted">${new Date(o.created_at).toLocaleString('ru-RU')}${admin?' · '+esc(o.customer):''}</p>${o.items.map(i=>`<div class="row"><span>${esc(i.name)} × ${i.quantity}</span><strong>${money(i.price*i.quantity)}</strong></div>`).join('')}<p><strong>Итого: ${money(o.total)}</strong></p>${o.comment?`<p>Комментарий: ${esc(o.comment)}</p>`:''}<div class="order-actions">${buttons}</div></article>`}
async function renderOrders(){const os=await api('/orders');$('#orders-content').innerHTML=os.length?os.map(o=>orderHTML(o,false)).join(''):'<p class="empty">У вас пока нет заказов. Начните с меню.</p>'}
let adminOrders=[];
async function renderAdmin(){adminOrders=await api('/admin/orders');$('#admin-orders').innerHTML=adminOrders.length?adminOrders.map(o=>orderHTML(o,true)).join(''):'<p class="empty">Заказов пока нет.</p>';$('#admin-dishes').innerHTML=state.dishes.map(d=>`<div class="row"><div><strong>${esc(d.name)}</strong><div class="muted">${esc(d.category)} · ${money(d.price)} · Остаток: ${d.stock}</div></div><button class="secondary" data-edit-dish="${d.id}">Редактировать</button></div>`).join('')}
function editDish(id){const d=state.dishes.find(d=>d.id===id)||{id:'',name:'',category:'Горячее',description:'',price:0,stock:0};const f=$('#dish-form');Object.keys(d).forEach(k=>{if(f.elements[k])f.elements[k].value=k==='price'?d[k]/100:d[k]});f.querySelector('.error').textContent='';$('#dish-dialog').showModal()}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-close')){b.closest('dialog').close();return}action(async()=>{if(b.dataset.view)return show(b.dataset.view);if(b.dataset.cat){state.category=b.dataset.cat;renderMenu()}if(b.dataset.add){if(!state.user){$('#auth-dialog').showModal();return}b.disabled=true;try{const id=+b.dataset.add;await api('/cart/'+id,'PUT',{quantity:(state.cart.find(i=>i.id===id)?.quantity||0)+1});await refresh();notice('Блюдо добавлено в корзину')}finally{b.disabled=false}}if(b.dataset.qty||b.dataset.remove){const id=b.dataset.qty||b.dataset.remove;const quantity=+(b.dataset.value||0);await api('/cart/'+id,quantity?'PUT':'DELETE',quantity?{quantity}:undefined);await renderCart()}if(b.dataset.cancel){if(!confirm('Отменить заказ и вернуть порции в меню?'))return;await api('/orders/'+b.dataset.cancel+'/cancel','POST',{});await refresh();await renderOrders();notice('Заказ отменён')}if(b.dataset.status){if(b.dataset.status==='cancelled'&&!confirm('Отменить этот заказ?'))return;await api('/admin/orders/'+b.dataset.order+'/status','PATCH',{status:b.dataset.status});await refresh();await renderAdmin();notice('Статус изменён')}if(b.dataset.editDish)editDish(+b.dataset.editDish);if(b.dataset.editItems){const o=adminOrders.find(o=>o.id===+b.dataset.editItems);$('#items-form').dataset.order=o.id;$('#items-fields').innerHTML=state.dishes.map(d=>`<label class="row"><span>${esc(d.name)} · ${money(d.price)}</span><input type="number" min="0" max="99" value="${o.items.find(i=>i.dish_id===d.id)?.quantity||0}" data-item-id="${d.id}" aria-label="Количество ${esc(d.name)}" required></label>`).join('');$('#items-form .error').textContent='';$('#items-dialog').showModal()}})});
$('#search').addEventListener('input',renderMenu);
$('#account').onclick=()=>action(async()=>{if(!state.user){$('#auth-dialog').showModal();return}await api('/auth/logout','POST',{});state.user=null;state.token=null;sessionStorage.removeItem('restaurant-token');await refresh();await show('menu');notice('Вы вышли из аккаунта')});
$('#auth-toggle').onclick=()=>{state.register=!state.register;$('#name-label').hidden=!state.register;$('#name-label input').required=state.register;$('#auth-title').textContent=state.register?'Создать аккаунт':'Вход в аккаунт';$('#auth-toggle').textContent=state.register?'Уже есть аккаунт':'Создать аккаунт';$('#auth-form [name=password]').autocomplete=state.register?'new-password':'current-password';$('#auth-error').textContent=''};
$('#auth-form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('[type=submit]');b.disabled=true;try{const x=await api('/auth/'+(state.register?'register':'login'),'POST',Object.fromEntries(new FormData(e.target)));state.user=x.user;state.token=x.token;sessionStorage.setItem('restaurant-token',x.token);$('#auth-dialog').close();e.target.reset();await refresh();notice('Здравствуйте, '+state.user.name+'!')}catch(err){$('#auth-error').textContent=err.message}finally{b.disabled=false}};
document.addEventListener('submit',e=>{if(e.target.id!=='checkout-form')return;e.preventDefault();action(async()=>{const b=e.target.querySelector('button');b.disabled=true;try{const o=await api('/orders','POST',{comment:$('#comment').value});await refresh();await show('orders');notice('Заказ № '+o.id+' принят')}finally{b.disabled=false}})});
$('#refresh-orders').onclick=()=>action(renderOrders);$('#refresh-admin').onclick=()=>action(async()=>{await refresh();await renderAdmin()});$('#new-dish').onclick=()=>editDish(0);
$('#dish-form').onsubmit=async e=>{e.preventDefault();const f=e.target,x=Object.fromEntries(new FormData(f)),id=x.id;delete x.id;x.price=Math.round(Number(x.price)*100);x.stock=Number(x.stock);try{await api('/admin/dishes'+(id?'/'+id:''),id?'PUT':'POST',x);$('#dish-dialog').close();await refresh();await renderAdmin();notice('Блюдо сохранено')}catch(err){f.querySelector('.error').textContent=err.message}};
$('#items-form').onsubmit=async e=>{e.preventDefault();const f=e.target;const items=[...f.querySelectorAll('[data-item-id]')].filter(i=>Number(i.value)>0).map(i=>({dish_id:+i.dataset.itemId,quantity:Number(i.value)}));try{await api('/admin/orders/'+f.dataset.order+'/items','PUT',{items});$('#items-dialog').close();await refresh();await renderAdmin();notice('Состав заказа обновлён')}catch(err){f.querySelector('.error').textContent=err.message}};
(async()=>{try{if(state.token){try{state.user=await api('/auth/me')}catch{state.token=null;sessionStorage.removeItem('restaurant-token')}}await refresh()}catch(e){notice(e.message);$('#dish-grid').innerHTML='<p class="empty">Меню недоступно. Запустите сервер и обновите страницу.</p>'}})();
